---
title: "Welcome"
description: A self-paced introduction to the R programming language for scientific work, covering data manipulation, transformation, and visualization.
---

## About this workshop

Welcome! This workshop will teach you the basics of R. Its structure is meant to support different levels of R expertise and interests: already know the basics and want to learn how to [plot](/qmd/plotting/plotting.qmd)? Want to freshen up your R skills and look at specific topics? Or are you new to programming with R and want to follow the course structure? This workshop provides different entry points. You can either follow the outline on the left side and work on all topics in the order they are presented in. Or, if you already have some R experience, you might want to read [The Big Picture](/qmd/getting-started/the-big-picture.qmd) and/or the [Final Exercise](./qmd/final-exercise/final-exercise.qmd) first to identify topics you want to work on.

[^1]: This workshop was designed by Nicklas Hafiz, PhD student and research fellow at the Institut für Qualitätsentwicklung im Bildungswesen (IQB).

::: {.callout-note collapse="true" icon="false"}
## Unfold if you want to learn more about optional content

Don't worry if you don't finish the whole workshop in time, or the material seems a bit overwhelming. It is designed to provide additional information for self studying. Optional input and exercises can be found in folded in sections like this one.
:::

The main objective of this workshop is to get you started with using R for your own scientific work. To do that, we will repeat and try out the main concepts multiple times, so you get to work with them as much and as from many different perspectives as possible. Along the way, some advanced ideas will be introduced as well, which you can follow up on later in case you think they might be relevant for your own work.

Each section is divided into a theory part and some exercises. 

::: callout-tip
Learning how to program can be tough. To get started it is important to write as much code as possible, and think about many different problems to get used to coding in the new language. So do the exercises!
:::

::: callout-warning
## Software installation

Please [install the necessary software](qmd/setup/setup.qmd) **before the workshop**.
:::

## Why R?

-   R is a popular programming language for data manipulation, statistical data analyses and plotting of data.
-   It is open source, and has a big community, which facilitates the development of additional [software packages](/qmd/packages/packages.qmd) for multiple different applications, but also makes it easy to get help if you are stuck at a particular problem.
-   This is one of the reasons why R is great for doing statistical analyses - there are packages for almost every use case.
-   It has great tools for making beautiful plots.
-   This is not R specific, but because you can write programs for your specific use cases, it facilitates many workflow related tasks like automation, tracking changes with git, result preparation with markdown/latex and many more.

There are many more reasons to learn R, as it is a very flexible tool for almost every aspect of scientific work (after all, I[^1] have created this whole workshop from within RStudio), so let's dive right in by [setting up](qmd/setup/setup.qmd) everything!

:::: {.columns}

::: {.column width="47.5%"}

::: {.callout-tip title="Support the LMU Open Science Center!"}

**Like this tutorial? Be sure to give [the repository]({{< meta repo-url >}}) a star and [follow us on GitHub](https://github.com/lmu-osc)!**
:::

:::

::: {.column width="5%"}
:::

::: {.column width="47.5%"}


::: {.callout-tip title="Questions about this tutorial?"}
**If you have questions for the author of this tutorial, please take a look at the [About](about.qmd) page.**
:::

:::

::::
