---
title: "Plotting: Exercises"
---


::: {.callout-caution icon="false" collapse="true"}
## Previous code
```{r, message = FALSE}
library(tidyverse)

## Load the data
characters <- readRDS(file = here::here("raw_data", "characters.rds"))
psych_stats <- read.csv(
  file = here::here("raw_data", "psych_stats.csv"),
  sep = ";"
)

## Reshape psych_stats into long format:
psych_stats <- psych_stats %>%
  pivot_longer(cols = messy_neat:innocent_jaded, 
               names_to = "question", 
               values_to = "rating")

## Merge it
characters_stats <- merge(
  x = characters,
  y = psych_stats,
  by.x = "id", 
  by.y = "char_id"
)
```
:::



Keep in mind we haven't really checked the questions etc, so there would be a lot more work done on such a data set before you could really extract something from it.

```{r}

questions <- unique(characters_stats$question)[1:15]

## Characters subset
characters_subset <- characters_stats %>% 
  filter(uni_name == "Breaking Bad", question %in% questions)


ggplot(data = characters_subset, 
       aes(x = rating, 
           y = question,
           colour = name)) +
  #facet_grid(. ~ name) +
  geom_point() +
  facet_grid(. ~ uni_name)

```
