---
title: "Getting an Overview: Exercises"
---

::: {.callout-caution icon="false" collapse="true"}
## Previous code

```{r, message = FALSE}
# install.packages("tidyverse")
# install.packages("here")

library(tidyverse)
library(here)

## Load the data
characters <- readRDS(file = here::here("raw_data", "characters.rds"))
psych_stats <- read.csv(
  file = here::here("raw_data", "psych_stats.csv"),
  sep = ";"
)
```
:::

## Exercise 1

Take a look at the `characters` data set. 

1. How many rows and how many columns does the data frame have?

::: {.callout-tip collapse="true"}
## Hint

Use `str()`.
:::

::: {.callout-caution collapse="true"}
## Solution

```{r}
str(characters)
```

The data frame has `r nrow(characters)` rows and `r ncol(characters)` columns.
:::

2.  What show are the first characters in the data frame from?

::: {.callout-tip collapse="true"}
## Hint

Use `head()`.
:::

::: {.callout-caution collapse="true"}
## Solution

```{r}
head(characters)
```
They are from Friends.
:::

